// src/pages/Host.vue
<template>
  <div>
    Players connected: {{ playerManager.connectedPlayers.value.size }}, room id:
    {{ roomId }}
  </div>

  <PlayerCursor
    v-for="player in playerManager.connectedPlayers.value"
    :id="player"
  />
</template>

<script setup lang="ts">
import { createHost } from "../lib/peer";
import PlayerCursor from "../components/PlayerCursor.vue";
import { providePlayers } from "../context/players";

const playerManager = providePlayers();

const host = createHost();
const { roomId } = host;

host.on("connect", (id) => playerManager.addPlayer(id));
host.on("disconnect", (id) => playerManager.removePlayer(id));

playerManager.host.value = host;

setInterval(() => {
  host.sendAll("ping", new Date().getTime());
}, 1000);
</script>

// src/pages/Host.tsx
import { Peer } from "peerjs";
import { createHost } from "../lib/peer";
import { For, createEffect, createSignal } from "solid-js";
import createPlayerManager from "../lib/playerManager";
import PlayerCursor from "../components/PlayerCursor";
import { setPlayerStore } from "../stores/players";

const Host = () => {
  const host = createHost();
  const { roomId } = host;

  const playerManager = createPlayerManager(host);
  setPlayerStore(playerManager);

  setInterval(() => {
    host.sendAll("ping", new Date().getTime());
  }, 1000);

  return (
    <>
      <div>
        Players connected: {playerManager.connectedPlayers().length}, room id:{" "}
        {roomId()}
      </div>
      <For each={playerManager.connectedPlayers()}>
        {(playerId) => <PlayerCursor id={playerId} />}
      </For>
    </>
  );
};

export default Host;
